### ISSUE TITLE
Unable to connect to share

### ISSUE THREAD

**Issue by codyswanson4** [hierynomus/smbj#177]
Hello, everybody,
I am working on adding SMB2/2.1/3 support to Apache Commons VFS using this library.  I have a fork on my GitHub [here](https://github.com/codyswanson4/commons-vfs), but in it's current state, I cannot connect to a server I spun up for testing.  The version of smbj being used is 0.2.0 and my stacktrace is below.

java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1EncodableVector.add(Lorg/bouncycastle/asn1/ASN1Encodable;)V

	at com.hierynomus.spnego.NegTokenInit.addMechTypeList(NegTokenInit.java:179)
	at com.hierynomus.spnego.NegTokenInit.write(NegTokenInit.java:91)
	at com.hierynomus.smbj.auth.NtlmAuthenticator.negTokenInit(NtlmAuthenticator.java:146)
	at com.hierynomus.smbj.auth.NtlmAuthenticator.authenticate(NtlmAuthenticator.java:70)
	at com.hierynomus.smbj.connection.Connection.authenticationRound(Connection.java:156)
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:126)
	at org.apache.commons.vfs2.provider.smb2.SMB2ClientFactory.createConnection(SMB2ClientFactory.java:20)
	at org.apache.commons.vfs2.provider.smb2.SMB2FileProvider.doCreateFileSystem(SMB2FileProvider.java:81)
	at org.apache.commons.vfs2.provider.smb2.SMB2FileProvider.findFile(SMB2FileProvider.java:52)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:804)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:760)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:709)
	at org.apache.commons.vfs2.provider.smb2.test.SMB2ProviderTestCase.getBaseTestFolder(SMB2ProviderTestCase.java:40)
	at org.apache.commons.vfs2.test.AbstractTestSuite.setUp(AbstractTestSuite.java:185)
	at org.apache.commons.vfs2.test.AbstractTestSuite$1.protect(AbstractTestSuite.java:148)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at org.apache.commons.vfs2.test.AbstractTestSuite.run(AbstractTestSuite.java:154)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Process finished with exit code 255

Any help in resolving this is appreciated!

**Comment by codyswanson4** [comment]
Updated smbj to version 0.3.0 same problem.

**Comment by ecki** [comment]
Looks like it is missing the bouncy castle dependencies.

**Comment by codyswanson4** [comment]
I added the following lines to the pom.xml file with no effect.
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>1.57</version>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk15on</artifactId>
      <version>1.57</version>
    </dependency>

**Comment by hierynomus** [comment]
What error do you get now that the dependencies are added. It should no longer throw the NoSuchMethodError

**Comment by codyswanson4** [comment]
It is still the same as before.

**Comment by hierynomus** [comment]
Then the dependencies aren't picked up, or somehow the dependency is downgraded. I've just looked at your commits, I don't see any mention of the added BC libraries...

**Comment by hierynomus** [comment]
What I do see in the main `pom.xml` is the following:

```
    <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk16</artifactId>
        <version>1.46</version>
      </dependency>
```

**Comment by codyswanson4** [comment]
I changed it since I committed last, so they won't show up on there.  I just pushed up my current project with the dependencies in the pom.xml file

**Comment by codyswanson4** [comment]
Alright, I got bouncycastle loaded.
